spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-reddit
    username: reddit_dev_user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    format-sql: true
    show-sql: true # Enable logging of SQL statements.
    database: mysql
    hibernate:
      ddl-auto: update # Defaults to create-drop when using embedded db and no schema detected. Otherwise defaults to none.

server:
  port: 8081