spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-reddit
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    format-sql: true
    show-sql: true # Enable logging of SQL statements.
    database: mysql
    hibernate:
      ddl-auto: update # Defaults to create-drop when using embedded db and no schema detected. Otherwise defaults to none.
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username:
    password:
    protocol: smtp
    ssl: no
    tls: yes
server:
  port: 8081

jwt:
  expiration:
    time: 900000
